//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusConclusion
    {
        public int ID_Conclusion { get; set; }
        public Nullable<int> ID_ConclusionType { get; set; }
        public string ConclusionName { get; set; }
        public string Explanation { get; set; }
        public string Suggestion { get; set; }
        public string DietGuide { get; set; }
        public string SportsGuide { get; set; }
        public string HealthKnowledge { get; set; }
        public Nullable<int> ForGender { get; set; }
        public string InputCode { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string TeamConclusionName { get; set; }
        public Nullable<int> ID_Createopr { get; set; }
        public string CreateOperator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IS_Banned { get; set; }
        public Nullable<int> ID_BanOpr { get; set; }
        public string BanOperator { get; set; }
        public Nullable<System.DateTime> BanDate { get; set; }
        public string BanDescribe { get; set; }
        public Nullable<int> ID_ICD { get; set; }
        public Nullable<int> ID_FinalConclusionType { get; set; }
    }
}
