//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusSpecimen
    {
        public int ID_Specimen { get; set; }
        public string SpecimenName { get; set; }
        public string InputCode { get; set; }
        public int DispOrder { get; set; }
        public string LisSpecimenName { get; set; }
    }
}
