//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnCustPhysicalExamInfo
    {
        public long ID_Customer { get; set; }
        public string CustomerName { get; set; }
        public Nullable<bool> Is_Team { get; set; }
        public Nullable<int> ID_Team { get; set; }
        public Nullable<int> Is_Paused { get; set; }
        public Nullable<bool> Is_SectionLock { get; set; }
        public Nullable<int> ID_ExamType { get; set; }
        public string ExamTypeName { get; set; }
        public Nullable<int> ID_Set { get; set; }
        public string SetName { get; set; }
        public Nullable<int> ID_ExamPlace { get; set; }
        public string ExamPlaceName { get; set; }
        public Nullable<int> ID_GuideNurse { get; set; }
        public string GuideNurse { get; set; }
        public Nullable<int> ID_ReportWay { get; set; }
        public string ReportWayName { get; set; }
        public Nullable<int> ID_FeeWay { get; set; }
        public string FeeWayName { get; set; }
        public Nullable<int> SecurityLevel { get; set; }
        public Nullable<int> DiseaseLevel { get; set; }
        public Nullable<bool> Is_FeeSettled { get; set; }
        public Nullable<bool> Is_GuideSheetPrinted { get; set; }
        public Nullable<bool> Is_GuideSheetReturned { get; set; }
        public Nullable<System.DateTime> GuideSheetReturnedDate { get; set; }
        public string GuideSheetReturnedby { get; set; }
        public Nullable<bool> Is_UseHideCode { get; set; }
        public Nullable<bool> Is_FinalFinished { get; set; }
        public Nullable<int> ID_FinalDoctor { get; set; }
        public string FinalDoctor { get; set; }
        public Nullable<System.DateTime> FinalDate { get; set; }
        public string FinalOverView { get; set; }
        public string FinalConclusion { get; set; }
        public string ResultCompare { get; set; }
        public string MainDiagnose { get; set; }
        public string FinalDietGuide { get; set; }
        public string FinalSportGuide { get; set; }
        public string FinalHealthKnowlage { get; set; }
        public Nullable<bool> Is_Checked { get; set; }
        public Nullable<int> ID_Checker { get; set; }
        public string Checker { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<bool> Is_ReportReceipted { get; set; }
        public Nullable<System.DateTime> SubScribDate { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public Nullable<int> ID_Operator { get; set; }
        public string Operator { get; set; }
        public string Note { get; set; }
        public Nullable<int> Is_Subscribed { get; set; }
        public string Invoice { get; set; }
        public Nullable<int> ID_UserGuideSheetReturnedBy { get; set; }
        public Nullable<int> ID_SubScriber { get; set; }
        public string SubScriber { get; set; }
        public Nullable<System.DateTime> SubScriberOperDate { get; set; }
        public Nullable<bool> Is_ExamStarted { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> ID_Gender { get; set; }
        public string GenderName { get; set; }
        public Nullable<int> ID_Marriage { get; set; }
        public string MarriageName { get; set; }
        public Nullable<int> ID_Nation { get; set; }
        public string NationName { get; set; }
        public Nullable<int> ID_Cultrul { get; set; }
        public string CultrulName { get; set; }
        public Nullable<int> ID_Vocation { get; set; }
        public string VocationName { get; set; }
        public string IDCard { get; set; }
        public string ExamCard { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public string DepartSubA { get; set; }
        public string DepartSubB { get; set; }
        public string DepartSubC { get; set; }
        public string IndicatorDiagnose { get; set; }
        public string OtherDiagnose { get; set; }
        public string SecondaryDiagnose { get; set; }
        public string NormalDiagnose { get; set; }
        public Nullable<int> Is_InternatSubscribe { get; set; }
        public string CustomerOrderNO { get; set; }
        public Nullable<bool> Is_DiseaseLevelInformed { get; set; }
        public Nullable<int> ID_DiseaseLevelInformer { get; set; }
        public string DiseaseLevelInformer { get; set; }
        public Nullable<System.DateTime> DiseaseLevelInformedDate { get; set; }
        public string DiseaseLevelInformNote { get; set; }
    }
}
