//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnCustFee
    {
        public int ID_CustFee { get; set; }
        public Nullable<long> ID_Customer { get; set; }
        public Nullable<int> ID_Fee { get; set; }
        public string FeeItemName { get; set; }
        public Nullable<int> ID_Register { get; set; }
        public string RegisterName { get; set; }
        public Nullable<System.DateTime> RegistDate { get; set; }
        public double OriginalPrice { get; set; }
        public Nullable<double> Discount { get; set; }
        public double FactPrice { get; set; }
        public Nullable<int> ID_Discounter { get; set; }
        public string DiscounterName { get; set; }
        public bool Is_FeeCharged { get; set; }
        public Nullable<int> ID_FeeCharger { get; set; }
        public string FeeCharger { get; set; }
        public Nullable<System.DateTime> FeeChargeDate { get; set; }
        public Nullable<bool> Is_FeeRefund { get; set; }
        public Nullable<int> ID_FeeRefunder { get; set; }
        public string FeeRefunder { get; set; }
        public Nullable<bool> Is_Examined { get; set; }
        public Nullable<int> ID_ExamDoctor { get; set; }
        public string ExamDoctorName { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<bool> Is_Discard { get; set; }
        public Nullable<int> ID_FeeType { get; set; }
        public Nullable<int> CustFeeChargeState { get; set; }
        public Nullable<System.DateTime> FeeRefunderDate { get; set; }
        public Nullable<int> Is_Printed { get; set; }
        public string ApplyID { get; set; }
        public string FeeImageUrl { get; set; }
    }
}
