//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnCustConclusion
    {
        public int ID_CustConclusion { get; set; }
        public Nullable<long> ID_Customer { get; set; }
        public string ConclusionName { get; set; }
        public string ConclusionTypeName { get; set; }
        public Nullable<bool> Is_NoEntrySuggestion { get; set; }
        public string Explanation { get; set; }
        public string Suggestion { get; set; }
        public string DietGuide { get; set; }
        public string SportGuide { get; set; }
        public string HealthKnowledge { get; set; }
        public Nullable<int> ID_Doctor { get; set; }
        public string DoctorName { get; set; }
        public System.DateTime ConclusionDate { get; set; }
        public Nullable<int> ID_Conclusion { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public Nullable<int> DiagnoseType { get; set; }
    }
}
