//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnCustReportManage
    {
        public int ID_ReportManage { get; set; }
        public Nullable<long> ID_Customer { get; set; }
        public Nullable<int> ID_ReprotWay { get; set; }
        public string ReportWay { get; set; }
        public Nullable<bool> Is_Informed { get; set; }
        public string Informer { get; set; }
        public Nullable<System.DateTime> InformedDate { get; set; }
        public Nullable<bool> Is_InformReturned { get; set; }
        public Nullable<bool> Is_ReportReceipted { get; set; }
        public Nullable<bool> Is_SelfReceipted { get; set; }
        public string ReportReceiptor { get; set; }
        public Nullable<System.DateTime> ReportReceiptedDate { get; set; }
        public Nullable<int> ID_ReportOffer { get; set; }
        public string ReportOffer { get; set; }
        public Nullable<bool> Is_ReportPrinted { get; set; }
        public Nullable<int> ID_ReportPrinter { get; set; }
        public string ReportPrinter { get; set; }
        public Nullable<System.DateTime> ReportPrintedDate { get; set; }
        public Nullable<int> ID_ReportChecker { get; set; }
        public string ReportChecker { get; set; }
        public Nullable<System.DateTime> ReportCheckDate { get; set; }
        public string ReportPosition { get; set; }
        public Nullable<int> ID_Informer { get; set; }
        public Nullable<int> ID_ReportReceiptor { get; set; }
        public Nullable<System.DateTime> ReportOffDate { get; set; }
    }
}
