//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnFianlCheck
    {
        public int ID_FinalCheck { get; set; }
        public Nullable<long> ID_Customer { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> ID_FinalDoctor { get; set; }
        public string FinalDoctor { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> ID_FinalCheckDoctor { get; set; }
        public string FinalCheckDoctor { get; set; }
        public Nullable<System.DateTime> FinaleCheckDate { get; set; }
        public Nullable<bool> Is_Pass { get; set; }
        public string RefuseReason { get; set; }
    }
}
