//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PEISEntities : DbContext
    {
        public PEISEntities()
            : base("name=PEISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusCustApply> BusCustApply { get; set; }
        public virtual DbSet<BusExamItem> BusExamItem { get; set; }
        public virtual DbSet<BusFeeExamItem> BusFeeExamItem { get; set; }
        public virtual DbSet<BusFeeItem> BusFeeItem { get; set; }
        public virtual DbSet<BusFeeReport> BusFeeReport { get; set; }
        public virtual DbSet<BusPEPackage> BusPEPackage { get; set; }
        public virtual DbSet<DictCountry> DictCountry { get; set; }
        public virtual DbSet<DictCultrul> DictCultrul { get; set; }
        public virtual DbSet<DictExamPlace> DictExamPlace { get; set; }
        public virtual DbSet<DictFeeWay> DictFeeWay { get; set; }
        public virtual DbSet<DictGender> DictGender { get; set; }
        public virtual DbSet<DictMarriage> DictMarriage { get; set; }
        public virtual DbSet<DictNation> DictNation { get; set; }
        public virtual DbSet<DictReceiveReportWay> DictReceiveReportWay { get; set; }
        public virtual DbSet<DictVocation> DictVocation { get; set; }
        public virtual DbSet<OnArcCust> OnArcCust { get; set; }
        public virtual DbSet<OnCustExamSection> OnCustExamSection { get; set; }
        public virtual DbSet<OnCustFee> OnCustFee { get; set; }
        public virtual DbSet<OnCustRelationCustPEInfo> OnCustRelationCustPEInfo { get; set; }
        public virtual DbSet<SysMenu> SysMenu { get; set; }
        public virtual DbSet<SYSOpUser> SYSOpUser { get; set; }
        public virtual DbSet<SYSRight> SYSRight { get; set; }
        public virtual DbSet<SysRole> SysRole { get; set; }
        public virtual DbSet<SysRoleRight> SysRoleRight { get; set; }
        public virtual DbSet<SYSSection> SYSSection { get; set; }
        public virtual DbSet<SYSUserRight> SYSUserRight { get; set; }
        public virtual DbSet<SYSUserRole> SYSUserRole { get; set; }
        public virtual DbSet<SYSUserSection> SYSUserSection { get; set; }
        public virtual DbSet<BusConclusion> BusConclusion { get; set; }
        public virtual DbSet<BusConclusionType> BusConclusionType { get; set; }
        public virtual DbSet<BusCustomerNum> BusCustomerNum { get; set; }
        public virtual DbSet<BusExamItemGroup> BusExamItemGroup { get; set; }
        public virtual DbSet<BusFee> BusFee { get; set; }
        public virtual DbSet<BusSetFeeDetail> BusSetFeeDetail { get; set; }
        public virtual DbSet<BusSpecimen> BusSpecimen { get; set; }
        public virtual DbSet<BusSymptom> BusSymptom { get; set; }
        public virtual DbSet<DictExamType> DictExamType { get; set; }
        public virtual DbSet<OnCustApply> OnCustApply { get; set; }
        public virtual DbSet<OnCustBackLog> OnCustBackLog { get; set; }
        public virtual DbSet<OnCustConclusion> OnCustConclusion { get; set; }
        public virtual DbSet<OnCustExamItem> OnCustExamItem { get; set; }
        public virtual DbSet<OnCustExamItemResult> OnCustExamItemResult { get; set; }
        public virtual DbSet<OnCustPhysicalExamInfo> OnCustPhysicalExamInfo { get; set; }
        public virtual DbSet<OnCustReportManage> OnCustReportManage { get; set; }
        public virtual DbSet<OnFianlCheck> OnFianlCheck { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<TeamTask> TeamTask { get; set; }
        public virtual DbSet<TeamTaskGroup> TeamTaskGroup { get; set; }
        public virtual DbSet<TeamTaskGroupCust> TeamTaskGroupCust { get; set; }
        public virtual DbSet<TeamTaskGroupFee> TeamTaskGroupFee { get; set; }
        public virtual DbSet<tempaa> tempaa { get; set; }
    }
}
