//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMenu
    {
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Url { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public Nullable<int> MenuLevel { get; set; }
        public string RightCode { get; set; }
        public Nullable<bool> Is_CombineWithSection { get; set; }
    }
}
