//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSOpUser
    {
        public int UserID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string UserName { get; set; }
        public string LoginName { get; set; }
        public string PassWord { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DisDate { get; set; }
        public byte[] Signature { get; set; }
        public Nullable<double> DisCountRate { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Is_Del { get; set; }
        public Nullable<int> VocationType { get; set; }
        public Nullable<int> OperateLevel { get; set; }
        public Nullable<int> TotalNum { get; set; }
        public Nullable<int> FailCount { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
