//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamTaskGroup
    {
        public int ID_TeamTaskGroup { get; set; }
        public Nullable<int> ID_TeamTask { get; set; }
        public string TeamTaskGroupName { get; set; }
        public int ID_Team { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> ForGender { get; set; }
        public Nullable<int> Is_Marriage { get; set; }
        public string MinAgeValue { get; set; }
        public string MaxAgeValue { get; set; }
        public Nullable<int> ID_ExamType { get; set; }
        public string ExamTypeName { get; set; }
        public Nullable<int> ID_Set { get; set; }
        public string SetName { get; set; }
        public Nullable<int> ID_FeeWay { get; set; }
        public string FeeWayName { get; set; }
        public Nullable<int> SecurityLevel { get; set; }
        public Nullable<bool> Is_GroupStarted { get; set; }
        public Nullable<int> Is_GroupPaused { get; set; }
        public string TeamTaskName { get; set; }
        public string RoleName { get; set; }
    }
}
