//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamTask
    {
        public int ID_TeamTask { get; set; }
        public Nullable<int> ID_Team { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<int> TaskNumCount { get; set; }
        public string Contact { get; set; }
        public string Tel { get; set; }
        public Nullable<int> ID_Subscriber { get; set; }
        public string Subscriber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> TaskExamStartDate { get; set; }
        public Nullable<System.DateTime> TaskExamEndDate { get; set; }
        public string InputCode { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string TeamTaskName { get; set; }
    }
}
